Repository soolung/simblue-client, pull requests merged in 2023-03, with the labels that each got.

#80 HOTFIX :: 회원가입 안되는 문제였으나
  src/components/ApplicationManagement/NoticeAside/NoticeAside.js
  src/components/Button/Button.js
  src/pages/Application/ApplicationDetail/ApplicationDetail.js
  src/pages/Create/Create.js
Labels: 🛠BugFix

#79 STYLE :: footer 위치
  src/pages/Form/Form.js
  src/pages/Form/Form.scss
Labels: 🛠BugFix

#83 Feat/owner
  public/images/basic-profile-image.svg
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Header/ProfilePopover/ProfilePopover.js
  src/components/Modal/AdvancedSetting/AdvancedSettingModal.js
  src/components/Modal/AdvancedSetting/AdvancedSettingModal.scss
  src/components/Modal/AdvancedSetting/Owner/Owner.js
  src/components/Modal/AdvancedSetting/Owner/Owner.scss
  src/components/Modal/AdvancedSetting/ResultSearch/ResultSearch.js
  src/components/Modal/AdvancedSetting/ResultSearch/ResultSearch.scss
  src/components/common/Date/DateBox.js
  src/components/common/Search/Search.js
  src/components/common/Search/Search.scss
  src/pages/Auth/Login.js
  src/pages/Form/Form.js
  src/pages/Main/Main.js
  src/utils/api/application.js
  src/utils/api/token.js
  src/utils/api/user.js
  src/utils/atom/user.js
  src/utils/constant/user.constant.js
Labels: ✨Feature

#78 신청 삭제 구현
  public/images/basic-profile-image.svg
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Header/ProfilePopover/ProfilePopover.js
  src/components/Modal/AdvancedSetting/AdvancedSettingModal.js
  src/components/Modal/AdvancedSetting/AdvancedSettingModal.scss
  src/components/Modal/AdvancedSetting/Owner/Owner.js
  src/components/Modal/AdvancedSetting/Owner/Owner.scss
  src/components/Modal/AdvancedSetting/ResultSearch/ResultSearch.js
  src/components/Modal/AdvancedSetting/ResultSearch/ResultSearch.scss
  src/components/common/Date/DateBox.js
  src/components/common/Search/Search.js
  src/components/common/Search/Search.scss
  src/pages/Auth/Login.js
  src/pages/Form/Form.js
  src/pages/Main/Main.js
  src/utils/api/application.js
  src/utils/api/token.js
  src/utils/api/user.js
  src/utils/atom/user.js
  src/utils/constant/user.constant.js
Labels: ✨Feature

#84 Feat/kind record
  src/components/ApplicationManagement/NoticeAside/NoticeAside.scss
  src/components/Modal/ConfirmModal/ConfirmModal.js
  src/components/Modal/ConfirmModal/ConfirmModal.scss
  src/components/Record/Card/Card.js
  src/components/Record/Card/Card.scss
  src/components/Record/RecordKanban/RecordKanban.js
  src/components/Record/RecordKanban/RecordKanban.scss
  src/components/Record/ReplyRecord/ReplyRecord.js
  src/components/Record/ReplyRecord/ReplyRecord.scss
  src/components/Record/TeacherApplication.js
  src/components/Record/TeacherApplication.scss
  src/index.js
  src/index.scss
  src/pages/Form/Form.js
  src/pages/Record/Record.js
  src/pages/Record/Record.scss
  src/reportWebVitals.js
  src/utils/axios/server.js
  src/utils/config/authorization.js
  src/utils/etc/DateTimeFormatter.js
  src/utils/etc/StatusDivision.js
Labels: ✨Feature

#87 Hotfix
  src/components/Modal/AdvancedSetting/AdvancedSettingModal.js
  src/pages/Application/ApplicationDetail/ApplicationDetail.js
  src/pages/Form/Form.js
  src/utils/axios/server.js
Labels: 🛠BugFix

#94 Chore/response
  src/components/ApplicationManagement/ResultTable/ResultTable.js
  src/pages/Application/ApplicationManagement/ApplicationManagement.js
  src/pages/Record/Record.js
Labels: 👾 Chore
