Repository soolung/simblue-client, pull requests merged in 2023-02, with the labels that each got.

#63 Chore
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/components/ApplicationManagement/NoticeAside/NoticeAside.scss
  src/components/Create/Answer/Answer.js
  src/components/Create/Question/Question.js
  src/components/Header/Header.js
  src/components/Header/HeaderWing/HeaderWing.js
  src/components/Header/HeaderWing/HeaderWing.scss
  src/components/Header/SideBar/SideBar.js
  src/components/Header/SideBar/SideBar.scss
  src/components/common/Check/Check.js
  src/components/common/Radio/Radio.js
  src/components/common/Text/Text.js
  src/pages/Application/ApplicationDetail/ApplicationDetail.scss
  src/pages/Create/Create.js
Labels: 💦Clean, ✨Feature

#65 HOTFIX :: application title 범람
  src/components/Application/Application.scss
  src/pages/Application/ApplicationDetail/ApplicationDetail.scss
  src/pages/Look/Look.scss
  src/pages/Main/Main.scss
Labels: 🛠BugFix

#67 Overflow SideBar
  src/components/Header/SideBar/SideBar.js
  src/pages/Auth/Login.scss
Labels: 🛠BugFix

#68 Fix Sidebar Overflow
  src/components/Header/SideBar/SideBar.js
  src/pages/Auth/Login.scss
Labels: 🌏 Deploy

#69 모바일 화면 100vh 깨짐
  src/App.js
  src/components/ApplicationManagement/NoticeAside/NoticeAside.scss
  src/components/Header/SideBar/SideBar.scss
  src/index.scss
  src/pages/Create/Create.scss
Labels: 🛠BugFix

#70 Hotfix mobile 100vh
  src/App.js
  src/components/ApplicationManagement/NoticeAside/NoticeAside.scss
  src/components/Header/SideBar/SideBar.scss
  src/index.scss
  src/pages/Create/Create.scss
Labels: 🌏 Deploy

#72 Chore
  src/components/ApplicationManagement/NoticeAside/NoticeAside.scss
  src/components/common/Check/Check.js
  src/components/common/Check/Check.scss
  src/components/common/Radio/Radio.js
  src/components/common/Radio/Radio.scss
Labels: 💦Clean, 🛠BugFix

#77 신청 수정 페이지
  src/App.js
  src/components/Header/Header.js
  src/components/common/Date/DateBox.js
  src/components/common/TextBox/TextBox.js
  src/pages/Application/ApplicationDetail/ApplicationDetail.js
  src/pages/Create/Create.js
  src/pages/Form/Form.js
  src/pages/Form/Form.scss
  src/utils/api/application.js
  src/utils/etc/DateTimeFormatter.js
Labels: ✨Feature
